[build]
  # Build command with corrected debugging echos
  command = "echo \"VITE_API_BASE_URL is: $VITE_API_BASE_URL\" && echo \"API_URL is: $API_URL\" && npm run build"

  # Directory with the built site, relative to the base directory
  publish = "dist"

  # Base directory
  base = "client"

# Proxy rule to redirect API calls to the Render server
[[redirects]]
  # The path on your Netlify site
  from = "/api/*"

  # The URL of your Render backend.
  # This value will be substituted from a Netlify environment variable.
  to = ":API_URL/api/:splat"

  # HTTP status code for the redirect
  status = 200

  # Force the redirect even if a file exists at the 'from' path
  force = true 